# Generated by Django 4.2.16 on 2024-12-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_remove_command_name_command_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='quantity',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
