# Generated by Django 4.2.16 on 2024-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
