MEETINGS = [
    {
        "date": "2024-10-24",
        "president": "Jacques DUMITRAN",
        "prayer1": "Bruno DI RICO",
        "prayer2": "Olivier RIVET",
        "song1": 30,
        "song2": 44,
        "song3": 55,
        "portion": "Ps. 103-104",
        "jewels": "Serge RERA",
        "jewels_title": "Il se souvient que nous sommes poussière",
        "pearls": "Mehdi REMAL",
        "reading1": "Luigi CATANIA",
        "reading2": "Patrick ROCHE",
        "reading3": "Brian N GUYEN",
        "alloc1_type": "1er contact",
        "alloc2_type": "Nouvelle visite",
        "alloc3_type": "Discours",
        "alloc4_type": "",
        "alloc1_duration": 3,
        "alloc2_duration": 4,
        "alloc3_duration": 5,
        "alloc4_duration": 0,
        "alloc1pupil_hall1": "Jonathan BOUCARDEY",
        "alloc1inter_hall1": "Martin HUMBRECHT",
        "alloc2pupil_hall1": "Jade GRAFF",
        "alloc2inter_hall1": "Delphine GRAFF",
        "alloc3pupil_hall1": "Richard BONNEZ",
        "alloc3inter_hall1": "",
        "alloc4pupil_hall1": "",
        "alloc4inter_hall1": "",
        "alloc1pupil_hall2": "Armelle THILLEROT",
        "alloc1inter_hall2": "Sonia AUGUSTIN",
        "alloc2pupil_hall2": "Sarah N GUYEN",
        "alloc2inter_hall2": "Séverine BLONDEAU",
        "alloc3pupil_hall2": "Lionel VIALA",
        "alloc4pupil_hall2": "",
        "alloc4inter_hall2": "",
        "alloc3inter_hall2": "",
        "alloc1pupil_hall3": "Brian N GUYEN",
        "alloc1inter_hall3": "",
        "alloc2pupil_hall3": "",
        "alloc2inter_hall3": "Serge ROCHE",
        "alloc3pupil_hall3": "",
        "alloc3inter_hall3": "",
        "alloc4pupil_hall3": "",
        "alloc4inter_hall3": "",
        "vcm1": "Salvatore MOSCATIELLO",
        "vcm2": "",
        "vcm3": "",
        "vcm1_duration": 15,
        "vcm2_duration": 0,
        "vcm3_duration": 0,
        "vcm1_title": "Connais-tu tes limites ?",
        "vcm2_title": "",
        "vcm3_title": "",
        "eba": "Pierre PEREZ",
        "eba_reader": "Robert FARRE",
        "supervisor": "",
        "special_speech": "",
        "parking": "xxxxxxxxxxxx",
        "entrance": "xxxxxxxxxxxx",
        "inside": "xxxxxxxxxxxx",
        "podium": "xxxxxxxxxxxx",
        "sono1": "xxxxxxxxxxxx",
        "sono2": "xxxxxxxxxxxx",
        "mic1": "xxxxxxxxxxxx",
        "mic2": "xxxxxxxxxxxx",
    },
    {
        "date": "2024-11-04",
        "president": "Salvatore MOSCATIELLO",
        "prayer1": "Jacques PETIT",
        "prayer2": "Matthieu PEREZ",
        "song1": 3,
        "song2": 84,
        "song3": 97,
        "portion": "Ps. 105",
        "jewels": "Quentin FABRY",
        "jewels_title": "Pour toujours, il se souvient de son alliance",
        "pearls": "Olivier RIVET",
        "reading1": "Olivier FRISSON",
        "reading2": "",
        "reading3": "",
        "alloc1_type": "1er contact",
        "alloc2_type": "1er contact",
        "alloc3_type": "Nouvelle visite",
        "alloc4_type": "Nouvelle visite",
        "alloc1_duration": 1,
        "alloc2_duration": 2,
        "alloc3_duration": 4,
        "alloc4_duration": 4,
        "alloc1pupil_hall1": "Martin HUMBERCHT",
        "alloc1inter_hall1": "Matthieu PEREZ",
        "alloc2pupil_hall1": "Florence FRISSON",
        "alloc2inter_hall1": "Murielle DUMITRAN",
        "alloc3pupil_hall1": "Cynthia RIVET",
        "alloc3inter_hall1": "Ysabelle PEREZ",
        "alloc4pupil_hall1": "Mirelda PEREZ",
        "alloc4inter_hall1": "Michèle PETIT",
        "alloc1pupil_hall2": "",
        "alloc1inter_hall2": "",
        "alloc4pupil_hall1": "",
        "alloc4inter_hall1": "",
        "alloc2pupil_hall2": "",
        "alloc2inter_hall2": "",
        "alloc3pupil_hall2": "",
        "alloc3inter_hall2": "",
        "alloc4pupil_hall2": "",
        "alloc4inter_hall2": "",
        "alloc1pupil_hall3": "",
        "alloc1inter_hall3": "",
        "alloc2pupil_hall3": "",
        "alloc2inter_hall3": "",
        "alloc3pupil_hall3": "",
        "alloc3inter_hall3": "",
        "alloc4pupil_hall3": "",
        "alloc4inter_hall3": "",
        "vcm1": "Eric NOWAK",
        "vcm2": "",
        "vcm3": "",
        "vcm1_duration": 15,
        "vcm2_duration": 0,
        "vcm3_duration": 0,
        "vcm1_title": "Des expressions de votre amour",
        "vcm2_title": "",
        "vcm3_title": "",
        "eba": "",
        "eba_reader": "",
        "supervisor": "Jean-Pierre SORIANO",
        "special_speech": "Comment devenir plus courageux dans la prédication de maison en maison",
        "parking": "xxxxxxxxxxxx",
        "entrance": "xxxxxxxxxxxx",
        "inside": "xxxxxxxxxxxx",
        "podium": "xxxxxxxxxxxx",
        "sono1": "xxxxxxxxxxxx",
        "sono2": "xxxxxxxxxxxx",
        "mic1": "xxxxxxxxxxxx",
        "mic2": "xxxxxxxxxxxx",
    },
]
