from django.db import models

class week_mettings(models.Model):
    date = models.DateField()
    president = models.TextField()
    prayer1 = models.TextField()
    prayer2 = models.TextField()
    song1 = models.IntegerField()
    song2 = models.IntegerField()
    song3 = models.IntegerField()
    portion = models.TextField()
    jewels = models.TextField()
    jewels_title = models.TextField()
    pearls = models.TextField()
    reading1 = models.TextField()
    reading2 = models.TextField()
    reading3 = models.TextField()
    alloc1_type = models.TextField(blank=True, null=True)
    alloc2_type = models.TextField(blank=True, null=True)
    alloc3_type = models.TextField(blank=True, null=True)
    alloc4_type = models.TextField(blank=True, null=True)
    alloc1_duration = models.IntegerField(blank=True, null=True)
    alloc2_duration = models.IntegerField(blank=True, null=True)
    alloc3_duration = models.IntegerField(blank=True, null=True)
    alloc4_duration = models.IntegerField(blank=True, null=True)
    alloc1pupil_hall1 = models.TextField(blank=True, null=True)
    alloc1inter_hall1 = models.TextField(blank=True, null=True)
    alloc2pupil_hall1 = models.TextField(blank=True, null=True)
    alloc2inter_hall1 = models.TextField(blank=True, null=True)
    alloc3pupil_hall1 = models.TextField(blank=True, null=True)
    alloc3inter_hall1 = models.TextField(blank=True, null=True)
    alloc4pupil_hall1 = models.TextField(blank=True, null=True)
    alloc4inter_hall1 = models.TextField(blank=True, null=True)
    alloc1pupil_hall2 = models.TextField(blank=True, null=True)
    alloc1inter_hall2 = models.TextField(blank=True, null=True)
    alloc2pupil_hall2 = models.TextField(blank=True, null=True)
    alloc2inter_hall2 = models.TextField(blank=True, null=True)
    alloc3pupil_hall2 = models.TextField(blank=True, null=True)
    alloc4pupil_hall2 = models.TextField(blank=True, null=True)
    alloc4inter_hall2 = models.TextField(blank=True, null=True)
    alloc3inter_hall2 = models.TextField(blank=True, null=True)
    alloc1pupil_hall3 = models.TextField(blank=True, null=True)
    alloc1inter_hall3 = models.TextField(blank=True, null=True)
    alloc2pupil_hall3 = models.TextField(blank=True, null=True)
    alloc2inter_hall3 = models.TextField(blank=True, null=True)
    alloc3pupil_hall3 = models.TextField(blank=True, null=True)
    alloc3inter_hall3 = models.TextField(blank=True, null=True)
    alloc4pupil_hall3 = models.TextField(blank=True, null=True)
    alloc4inter_hall3 = models.TextField(blank=True, null=True)
    vcm1 = models.TextField()
    vcm2 = models.TextField(blank=True, null=True)
    vcm3 = models.TextField(blank=True, null=True)
    vcm1_duration = models.IntegerField()
    vcm2_duration = models.IntegerField(blank=True, null=True)
    vcm3_duration = models.IntegerField(blank=True, null=True)
    vcm1_title = models.TextField()
    vcm2_title = models.TextField(blank=True, null=True)
    vcm3_title = models.TextField(blank=True, null=True)
    eba = models.TextField(blank=True, null=True)
    eba_reader = models.TextField(blank=True, null=True)
    supervisor = models.TextField(blank=True, null=True)
    special_speech = models.TextField(blank=True, null=True)
