# Generated by Django 4.2.16 on 2024-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='content2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='content3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
