# Generated by Django 4.2.16 on 2024-12-05 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0004_alter_person_cong_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredicationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('place', models.TextField(max_length=255)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='persons.person')),
            ],
        ),
    ]
