# Generated by Django 4.2.16 on 2024-12-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_cong_status'),
        ('predication', '0003_rename_place_predicationmeeting_place1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicationmeeting',
            name='manager2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager2', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='predicationmeeting',
            name='manager3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager3', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='predicationmeeting',
            name='place2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='predicationmeeting',
            name='place3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='predicationmeeting',
            name='time2',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predicationmeeting',
            name='time3',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
