# Generated by Django 4.2.16 on 2025-01-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_person_cong_status'),
        ('predication', '0004_alter_predicationmeeting_manager2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicationmeeting',
            name='manager1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager1', to='persons.person'),
        ),
    ]
