# Generated by Django 4.2.16 on 2025-01-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predication', '0005_alter_predicationmeeting_manager1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predicationmeeting',
            old_name='manager1',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='predicationmeeting',
            old_name='place1',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='predicationmeeting',
            old_name='time1',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='manager2',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='manager3',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='place2',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='place3',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='predicationmeeting',
            name='time3',
        ),
    ]
