# Generated by Django 3.1.6 on 2024-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='vcm1_title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='vcm2_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='vcm3_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
