# Generated by Django 4.2.16 on 2024-11-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_role'),
        ('vcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='inter0_hall3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a0i_h3', to='persons.person'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pupil0_hall3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a0p_h3', to='persons.person'),
        ),
    ]
