# Generated by Django 3.1.6 on 2024-11-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='mic1',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='mic2',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='podium',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='sono1',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='sono2',
        ),
    ]
