# Generated by Django 4.2.16 on 2024-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='alloc1_type',
            field=models.CharField(choices=[('FIRST_CONTACT', '1er contact'), ('RETURN_VISIT', 'Nouvelle visite'), ('STUDY', 'Cours biblique'), ('DISCUSS', 'Discussion'), ('SPEECH', 'Discours'), ('VIDEO', 'Vidéo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2_type',
            field=models.CharField(choices=[('FIRST_CONTACT', '1er contact'), ('RETURN_VISIT', 'Nouvelle visite'), ('STUDY', 'Cours biblique'), ('DISCUSS', 'Discussion'), ('SPEECH', 'Discours'), ('VIDEO', 'Vidéo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc3_type',
            field=models.CharField(blank=True, choices=[('FIRST_CONTACT', '1er contact'), ('RETURN_VISIT', 'Nouvelle visite'), ('STUDY', 'Cours biblique'), ('DISCUSS', 'Discussion'), ('SPEECH', 'Discours'), ('VIDEO', 'Vidéo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc4_type',
            field=models.CharField(blank=True, choices=[('FIRST_CONTACT', '1er contact'), ('RETURN_VISIT', 'Nouvelle visite'), ('STUDY', 'Cours biblique'), ('DISCUSS', 'Discussion'), ('SPEECH', 'Discours'), ('VIDEO', 'Vidéo')], max_length=20, null=True),
        ),
    ]
