# Generated by Django 3.1.6 on 2024-11-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20241104_1615'),
        ('vcm', '0002_auto_20241104_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='alloc2inter_hall2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a2i_h2', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2inter_hall3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a2i_h3', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2pupil_hall2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a2p_h2', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2pupil_hall3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a2p_h3', to='persons.person'),
        ),
    ]
