# Generated by Django 3.1.6 on 2024-11-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20241104_1615'),
        ('vcm', '0003_auto_20241104_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='advisor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_advisor2', to='persons.person'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='advisor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_advisor3', to='persons.person'),
        ),
    ]
