# Generated by Django 3.1.6 on 2024-11-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20241104_1615'),
        ('vcm', '0004_auto_20241105_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='alloc1inter_hall3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='alloc2inter_hall3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='alloc3inter_hall3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='alloc3pupil_hall3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='alloc4inter_hall3',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='alloc4pupil_hall3',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2pupil_hall3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a1i_h3', to='persons.person'),
        ),
    ]
