# Generated by Django 3.1.6 on 2024-11-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_gender'),
        ('vcm', '0005_auto_20241112_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='alloc1inter_hall1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a1i_h1', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='alloc2inter_hall1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_a2i_h1', to='persons.person'),
        ),
    ]
