# Generated by Django 4.2.16 on 2024-11-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendmeeting',
            name='prayer1',
        ),
        migrations.RemoveField(
            model_name='weekendmeeting',
            name='prayer2',
        ),
    ]
