# Generated by Django 4.2.16 on 2024-11-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_role'),
        ('we', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendmeeting',
            name='foreign_speaker',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weekendmeeting',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings_as_we_speaker', to='persons.person'),
        ),
    ]
