# Generated by Django 4.2.16 on 2024-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'homme'), ('FEMALE', 'femme')], default='MALE', max_length=6)),
                ('cong_function', models.TextField(blank=True, max_length=20, null=True)),
                ('cong_roles', models.JSONField(verbose_name=models.TextField(max_length=100))),
                ('cong_status', models.TextField(blank=True, max_length=5, null=True)),
                ('group', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
