# Generated by Django 3.1.6 on 2024-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('cong_functions', models.TextField(blank=True, max_length=20, null=True)),
                ('cong_roles', models.JSONField(verbose_name=models.TextField(max_length=100))),
                ('cong_status', models.JSONField(verbose_name=models.TextField(blank=True, max_length=5, null=True))),
            ],
        ),
    ]
