# Generated by Django 3.1.6 on 2024-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
