# Generated by Django 4.2.16 on 2024-11-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cong_function',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('ELDER', 'Ancien'), ('ASSISTANT', 'Assistant')], max_length=9, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cong_roles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rôles'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cong_status',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('UNBAPT_PUBLISHER', 'PNB'), ('PUBLISHER', 'PROCL'), ('TEMPORARY', 'PA'), ('PERMANENT', 'PP'), ('SPECIAL', 'PS')], max_length=16, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Homme'), ('FEMALE', 'Femme')], max_length=6, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
