# Generated by Django 3.1.6 on 2024-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cong_status',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
