# Generated by Django 3.1.6 on 2024-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20241104_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'homme'), ('FEMALE', 'femme')], default='MALE', max_length=6),
        ),
    ]
