# Generated by Django 4.2.16 on 2024-12-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_cong_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cong_status',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Etudiant'), ('UNBAPT_PUBLISHER', 'Proclamateur non baptisé'), ('PUBLISHER', 'Proclamateur'), ('TEMPORARY', 'Pionnier auxiliaire'), ('PERMANENT', 'Pionnier permanent'), ('SPECIAL', 'Pionnier spécial')], max_length=16, null=True, verbose_name='Statut'),
        ),
    ]
